



CREATE DATABASE DWH;

DROP SCHEMA IF EXISTS bronzelayer CASCADE;
CREATE SCHEMA bronzelayer;

DROP SCHEMA IF EXISTS silverlayer CASCADE;
CREATE SCHEMA silverlayer;

DROP SCHEMA IF EXISTS goldlayer CASCADE;
CREATE SCHEMA goldlayer;
